# This workflow will build and test
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-tests:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
      
    - name: Build-RTSUIKit-iOS
      run: xcodebuild -scheme DolbyIORTSUIKit -destination "generic/platform=iOS Simulator"

    - name: Run tests
      run: xcodebuild test -scheme DolbyIORTSUIKit-Package -destination "platform=iOS Simulator,OS=15.0,name=iPhone 13 Pro"
